#!/bin/sh

# This script creates an rsa key pair for setting up ssh access to a remote machine.
# The private key file is copied to ~/.ssh/id_rsa.
# The public key file will end up parallel to the script and .

# Arguments
# ARG1  The name of the machine that uses the key. Should be something like myMachine_ssh_key.rsa

set -e

# create the key files
PRIVATE_KEY_FILE=$1_ssh_key.rsa
PUBLIC_KEY_FILE=$PRIVATE_KEY_FILE.pub

# cleanup old files
rm -f ~/$PRIVATE_KEY_FILE
rm -f ~/$PUBLIC_KEY_FILE

# generate new files
cd ~/
ssh-keygen -t rsa -N '' -C "Generated by $1" -f "$PRIVATE_KEY_FILE"

# copy the private file to the .ssh directory to use it
mkdir -p ~/.ssh
rm -f ~/.ssh/id_rsa
cp ~/$PRIVATE_KEY_FILE ~/.ssh/id_rsa

# also copy the public file to the .ssh directory for documentation purposes
rm -f ~/.ssh/$PUBLIC_KEY_FILE
cp ~/$PUBLIC_KEY_FILE ~/.ssh/$PUBLIC_KEY_FILE
