#!/bin/sh -
#
# This script shuts down the virtual machines and docker container of
# the CMakeProjectFramework build infrastrukture.
# This script is called by systemd via the /etc/systemd/system/shutdownVms.service file.
# On the build host, this file should be placed under /usr/bin

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/lib/virtualbox

start() {
  
  docker start cpf-web-server
  docker start jenkins-master
  docker start jenkins-slave-linux-0

  return 0
}

stop() {
  echo "-------- Waiting for virtual machines to power off... --------"
  echo $PATH
  
  sudo -u knitschi -H sh -c "VBoxManage controlvm BuildKnechtWin-2016-08-11 acpipowerbutton"

  until $(sudo -u knitschi -H sh -c "VBoxManage showvminfo BuildKnechtWin-2016-08-11 --machinereadable" | grep -q ^VMState=.poweroff.)
  do
      sleep 2
  done

  docker stop jenkins-slave-linux-0
  docker stop jenkins-master
  docker stop cpf-web-server


  return 0
}

case $1 in
  start|stop) "$1" ;;
esac

exit 0
