#!/bin/bash
#
# This script is run by git after a push has been made to the repository

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# The information about pushed branches is given to script over the input stream
# This stream contains a line for each branch that was pushed.
# Each line looks something like 2b3a00c587a4df993d608b82ab31321b88037dc9 18f998b61f0fe5069e5666a33863b70bf44a12f8 refs/heads/Knitschi-master
# Where the first hash probably marks the first pushed commit and the second the last pushed commit.
# The last element contains the name of the branch.
while read oldrev newrev refname
do
    bash $scriptDir/triggerJenkinsJob.sh $refname # pass all arguments except the first on to the triggerJenkinsJob.sh script 
done
